apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "your-super-secret-jwt-key-change-in-production-minimum-32-characters"
  redis-password: ""