apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secrets
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.config.jwt.secret | quote }}
  redis-password: {{ .Values.config.redis.password | quote }}