version: 1.54.0

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - revive
    - gosec
    - gocritic
    - gocyclo
    - dupl
    - bodyclose
    - noctx
    - exportloopref

  disable:
    - deadcode
    - varcheck
    - structcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true